### ISSUE TITLE
better to use sudo before apt-get & dpkg?

### ISSUE THREAD

**Issue by eleree** [iofu728/zsh.sh#1]
RT

**Comment by iofu728** [comment]
Thx, I will update it.

In designing, I was thinking about the size of docker images.
you know, in Linux distribution, `sudo` is a software. 
It not in docker ubuntu image.
It means that you will install sudo before to do that thing.
It spends lots.
And `sudo -i` will result in an interrupt.

**Comment by iofu728** [comment]
This problem has fix in #4 🚜prepare for version 0.1.3
