### ISSUE TITLE
wget: command not found && truncate: command not found

### ISSUE THREAD

**Issue by kklives** [iofu728/zsh.sh#11]
brew 安装之前是没有 wget 和 truncate 的，运行你的脚本前我必须得手动编译安装一下 brew 和 truncate 。。。

**Comment by iofu728** [comment]
the brew will be installed in this script If your macOS don't have brew in [https://github.com/iofu728/zsh.sh/blob/master/zsh.sh#L113](https://github.com/iofu728/zsh.sh/blob/master/zsh.sh#L113).

```shell
# Homebrew
if [ -z "$(which brew | sed -n '/\/brew/p')" ]; then
    echo_color yellow "${SIGN_2} ${DOW} homebrew ${SIGN_2}"
    wget ${HOMEBREW_URL}
    echo_color yellow "${SIGN_2} ${INS} homebrew ${SIGN_2}"
    /usr/bin/ruby install

    echo_color green "${SIGN_1} ${INS} git ${SIGN_1}"
    brew install git

    cd "$(brew --repo)"
    git remote set-url origin ${HOMEBREW_TUNA}brew.git
    cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
    git remote set-url origin ${HOMEBREW_TUNA}homebrew-core.git
fi
```

But I forget to check and install truncate before running other scripts indeed. And it fixes in the [#12 🐣fix truncate rely upon](#12 ) pull request

Sorry, thank you for your remind.
