### ISSUE TITLE
osx 10.14 - 10.15 vim crash

### ISSUE THREAD

**Issue by kklives** [iofu728/zsh.sh#14]

**Comment by iofu728** [comment]
It seems like the bug of OSX 10.15. 
I also encountered vim crash problem in Oct. 2019. And the CPU will be occupied a core.
Reinstall vim help me solve this problem.

If you have other problems, post the vim version and error log.

my vim version
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 29 2020 01:58:33)
macOS version
```
