### ISSUE TITLE
Is there need to install zsh and reboot first?

### ISSUE THREAD

**Issue by ghost** [iofu728/zsh.sh#7]
I use your script on Azure's centos VPS, an error occurred while running the following command:

```
wget https://raw.github.com/iofu728/zsh.sh/master/zsh.sh
bash zsh.sh &&  source  $ {ZDOTDIR ： - $ HOME } /.zshrc
bash zsh.sh &&  source  $ {ZDOTDIR ： - $ HOME } /.zshrc
```

I checked my shell has been changed to zsh (use `echo $SHELL`), 

after that, I restarted vps and then ran the script again, and this time it works!

My question: as the title says, Is it must install zsh and restart the vps before running the script ?

**Comment by iofu728** [comment]
In fact, It's to install the zsh and other packages when the first time run zsh.sh. And the source is to take effect the change.

Maybe there are some limitations in Azure VPS that the script can't take effect the change.

I'll test the script in Azure. Thx your issue.👏

**Comment by iofu728** [comment]
I have tested in Azure VPS(B1S, Ubuntu 18.04LTS). And I didn't encounter the situation you reported.

Maybe you not in root account.
