### ISSUE TITLE
xcode-select: error: command line tools are already installed

### ISSUE THREAD

**Issue by kklives** [iofu728/zsh.sh#9]
osx 10.14 运行报错 xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by iofu728** [comment]
Thank U, I forget to check the situation of Xcode install.

Now, I fix this bug in the pull request ([🦆fix macos xcode-select install #10](#10)) .

But I can't ensure the version of macOS doesn't have another bug, though I test in my mac book of 10.15.
